### ISSUE TITLE
Hi there,

### ISSUE THREAD

**Issue by ghost** [prog666/docxtemplater-chart-module#4]
is the module working now? 

I have npm installed it successfully, included the module, but I get 

Error: Cannot find module 'docxtemplater-chart-module'

error in my console.

**Comment by dderg** [comment]
check everything again, is there folder 'docxtemplater-chart-module' in 'node_modules'? module is working for me.

**Comment by ghost** [comment]
Everything seems to be all right, the folder is there. 
I also have docxtemplater in use already. It is version 1.0.8, can there be any conflict or something? But it seems improbable to me..

**Comment by dderg** [comment]
i'm not sure about compatibility.. only tested in latest version

**Comment by dderg** [comment]
Did you find the reason of this issue?

**Comment by ghost** [comment]
No, but I wasnt trying since then.

Dne 12. 11. 2015 v 14:54 Danila Dergachev napsal(a):

**Comment by cofesun** [comment]
I can not find js/index.js file. 
Error: Can not find module 'doctemplater-chart-module'.
