### ISSUE TITLE
npm published incorrectly?

### ISSUE THREAD

**Issue by Nedlinin** [prog666/docxtemplater-chart-module#8]
Trying to pull the library from npm using npm install docxtemplater-chart-module pulls files but leaves out the JS folder.  This means you get missing module errors.  

I had to pull the repo and manually build and put the files into the node_modules folder.

**Comment by dderg** [comment]
have any ideas how to fix this?

**Comment by Nedlinin** [comment]
I don't know a ton about publishing to npm but I believe the issue is that npm will pull this git repo for the files but you have the .gitignore containing an ignore for the js folder.  

So, when npm pulls the repo, the repo simply doesn't contain the js files needed.

**Comment by dderg** [comment]
but js files are compiled and should not be pushed to the repo

**Comment by dderg** [comment]
can you ask @edi9999 how did he done it?

**Comment by Nedlinin** [comment]
Yea.. Like I said I don't know much about npm publishing.  But, I did just push a test module out to npm to verify how it works and I'd say your repo is setup properly.

However, I did find some older threads of people stating this is sometimes an issue with npm (specifically older version <3).  Recommended fix is bumping the version number and republishing.  Might be worth a shot.

**Comment by dderg** [comment]
try again

**Comment by Nedlinin** [comment]
@prog666 :+1: Looks good this time.  I get the js folder with contents as expected!

**Comment by edi9999** [comment]
The .npmignore (https://github.com/prog666/docxtemplater-chart-module/blob/master/.npmignore) overrides the .gitignore file for npm, that's why the js folder should be published. It seems to be a bug with older versions of npm (which I never experienced)
